name: se_mobile
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logoM.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/medica_logo.png
    - assets/images/doctor.png
    - assets/images/tbib.png
    - assets/images/doctr.png
    - assets/images/logoM.png