name: se_mobile
description: Application Flutter avec Hive
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Base de données Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Sélection et manipulation d'images
  image_picker: ^1.2.1

  # Format de date et internationalisation
  intl: ^0.20.2

  # Accès aux répertoires système
  path_provider: ^2.1.0

  # Icons
  cupertino_icons: ^1.0.8

  # Stockage local
  shared_preferences: ^2.5.4

  # File picker
  file_picker: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/medica_logo.png
    - assets/images/doctr.png
    - assets/images/tbib.png
    - assets/images/doctor.png
    - assets/images/logoM.png
